export const demoAcademy = {
  id: "thebaeum-prime",
  slug: "thebaeum-prime",
  name: "더배움프라임영수학원",
  displayName: "더배움프라임영수학원 운영 보드",
  category: "영어 · 수학 전문 학원",
  naverPlaceId: "1298554109",
  address: "충남 아산시 탕정면 한들물빛5로 17 트윈시티2 603호, 604호",
  nearestStation: "탕정역 1번 출구에서 187m",
  businessHours: "23:00 운영 종료",
  visitorReviewCount: 16,
  blogReviewCount: 29,
  brandColor: "#047857",
  senderName: "더배움프라임",
  stats: {
    students: 200,
    staff: 16,
    classesToday: 8,
    pendingFollowups: 4,
  },
};
